name: treasure_hunt
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^0.7.0
  cupertino_icons: ^0.1.2
  flame: ^0.10.1
  sensors: ^0.4.0+1
  equatable: ^0.1.0
  permission: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
          weight: 700
  assets:
    - assets/images/bg.jpg
    - assets/images/fg.png
    - assets/images/magnifying_glass.png
    - assets/images/bus.png
    - assets/images/polaroid.png
    - assets/images/flower.png
    - assets/images/banner.png
    - assets/images/btn_next_level.png
    - assets/images/bear_head.png
    - assets/images/bear_body.png
    - assets/audio/level_1.mp3
    - assets/audio/level_2.mp3
    - assets/audio/level_3.mp3
    - assets/audio/before_game.mp3
    - assets/audio/during_game.mp3
    - assets/audio/end_game.mp3
    - assets/audio/level_end.mp3
